In [1]:
3 + 5 * 4

23

In [2]:
#Using Python as a calculator

In [3]:
print(weight_kg)

NameError: name 'weight_kg' is not defined

In [4]:
weight_kg = 60

In [5]:
print(weight_kg)

60


In [9]:
weight_kg_text = 'weight in kilograms:'
print(weight_kg_text, weight_kg)
print('weight in pounds:', weight_kg * 2.2)

weight in kilograms: 60
weight in pounds: 132.0


In [10]:
first, second = 'Grace', 'Shawn'

In [11]:
import numpy

In [14]:
medical_data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [15]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [17]:
import numpy as np
medical_data = np.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [21]:
#array
a = [1,2,3,4]

In [19]:
print(a)

[1, 2, 3, 4]


In [20]:
print(a[0])

1


In [22]:
print(type(medical_data))

<class 'numpy.ndarray'>


In [23]:
#data types
##ints = 3, 6, 100
##floating point numbers: 2.3, 4.322, 5.322

In [25]:
print(medical_data.shape)
#(rows, col)

(54, 40)


In [26]:
print('first value in medical data:',medical_data[0,0])

first value in medical data: 0.0


In [27]:
print('middle value in data:',medical_data[30,20])

middle value in data: 6.0


In [29]:
med_data_shape = medical_data.shape

In [30]:
print(med_data_shape)

(54, 40)


In [31]:
print(med_data_shape[0])

54


In [32]:
print(med_data_shape[1])

40


In [40]:
middle_row = int(med_data_shape[0]/2)

In [41]:
middle_col = int(med_data_shape[1]/2)

In [42]:
print(middle_row, middle_col)

27 20


In [43]:
print('actual middle of dataset:', medical_data[middle_row, middle_col])

actual middle of dataset: 6.0


In [44]:
print(medical_data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]]


In [45]:
bruin = medical_data[:3, 36:]

In [46]:
print(bruin)

[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [47]:
print('bruin is:\n',bruin)

bruin is:
 [[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


In [49]:
print(np.mean(medical)data)

SyntaxError: invalid syntax (<ipython-input-49-0232c8237637>, line 1)

In [51]:
import time
print(time.ctime())
#don't need anything in the parenthesis for some things

Mon Jan 27 09:42:45 2020


In [52]:
maxval, minval = np.max(medical_data), np.min(medical_data)

In [53]:
stdval = np.std(medical_data)

In [54]:
print('max:',maxval,', min:',minval,',stdev:',stdval)

max: 19.0 , min: 0.0 ,stdev: 4.352194529455482


In [55]:
patient_0 = medical_data[0,:]

In [56]:
print(patient_0)

[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.  3.  3. 10.  5.  7.  4.  7.  7.
 12. 18.  6. 13. 11. 11.  7.  7.  4.  6.  8.  8.  4.  4.  5.  7.  3.  4.
  2.  3.  0.  0.]


In [57]:
print('max inflammation for patient 0:', np.max(patient_0))

max inflammation for patient 0: 18.0


In [58]:
patient_2 = medical_data[1,:]
patient_2_min = np.min(patient_2)
print(patient_2_min)

0.0


In [59]:
print(np.mean(medical_data, axis=1))

[5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1  ]


In [63]:
#axis = 0 ~> gives us whatever function for each day (column-down)
#axis = 1 ~> gives us whatever function for each patient (row-across)
patient_means_down = np.mean(medical_data, axis=0)
print(patient_means_down)

[ 0.          0.66666667  1.33333333  2.33333333  2.          1.66666667
  4.33333333  3.66666667  5.          6.          6.          7.
  6.33333333  6.33333333  5.          7.66666667  6.33333333 11.33333333
  9.66666667 11.33333333 14.33333333 10.33333333 11.66666667 11.
  8.66666667  8.66666667  8.66666667  6.          7.66666667  4.33333333
  5.66666667  4.66666667  4.33333333  4.33333333  3.33333333  4.
  1.66666667  2.          0.33333333  0.66666667]


In [64]:
patient_means_down = np.mean(medical_data, axis=0)
print(patient_means_down.shape)

(40,)


In [65]:
patient_means_down = np.mean(medical_data, axis=1)
print(patient_means_down)

[5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1   5.45  5.425 6.1
 5.45  5.425 6.1   5.45  5.425 6.1  ]


In [68]:
#gives the length
patient_means_down = np.mean(medical_data, axis=0)
print(len(patient_means_down))

40


In [69]:
#To write a function
def my_func(name):
    print('Hello', name)
    

In [70]:
my_func("shawn")

Hello shawn


In [71]:
def square_minus(x):
    square = x*x
    square = square - 2
    return(square)

In [72]:
zzz = square_minus(4)
print(zzz)

14


In [73]:
def square_minus(x, y, name):
    my_func(name)
    return((x*y)-2)

In [74]:
zzz = square_minus(10,1,"Shawn")
print(zzz)

Hello Shawn
8


In [75]:
element = 'oxygen'

In [76]:
print ('first three characters:', element [0:3])

first three characters: oxy


In [77]:
print ('last three characters:', element[3:6])

last three characters: gen


In [78]:
print (element[:4])

oxyg


In [79]:
print (element[4:])

en


In [80]:
print (element[:])

oxygen


In [81]:
print (element [-1])

n


In [82]:
print (element[-2])

e


In [83]:
print (element[1:-1])

xyge


In [84]:
print (element[3:3])

In [85]:
print (element[3:3, 4:4])

TypeError: string indices must be integers

In [86]:
print (medical_data[3:3])

[]


In [87]:
print (medical_data[3:3, 4:4])

[]


In [88]:
print (medical_data[3:3, :])

[]


In [90]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [91]:
print(medical_data[1:2])

[[ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]]


In [92]:
print(type(medical_data))

<class 'numpy.ndarray'>


In [93]:
print(medical_data[3:3])

[]


In [94]:
print(medical_data[3:3, :])

[]


In [95]:
print(medical_data.shape)

(54, 40)


In [96]:
npdiff = numpy.array([medical_data])

In [98]:
X = numpy.diff(npdiff)

In [110]:
print (numpy.diff(npdiff))

[[[  1.   1.  -1.   1.  -1.   2.  -1.   0.   4.   4.   1.  -6.   4.  -5.
     0.   3.   9.  -8.  -2.  12. -14.   8.  -7.   7.  -5.   4.  -6.   6.
    -8.   0.   2.  -1.   0.   1.   0.  -4.   0.  -1.   1.]]]


In [102]:
print(medical_data[1:2])

[[ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6. 10. 11.  5.  9.  4.  4.  7. 16.
   8.  6. 18.  4. 12.  5. 12.  7. 11.  5. 11.  3.  3.  5.  4.  4.  5.  5.
   1.  1.  0.  1.]]


In [103]:
A = (medical_data[1:2])

In [104]:
npdiff = numpy.array([A])

In [105]:
B = numpy.diff(npdiff)

In [106]:
print (B)

[[[  1.   1.  -1.   1.  -1.   2.  -1.   0.   4.   4.   1.  -6.   4.  -5.
     0.   3.   9.  -8.  -2.  12. -14.   8.  -7.   7.  -5.   4.  -6.   6.
    -8.   0.   2.  -1.   0.   1.   0.  -4.   0.  -1.   1.]]]


In [107]:
print(B.shape)

(1, 1, 39)


In [108]:
print(A.shape)

(1, 40)


In [111]:
print(B)

[[[  1.   1.  -1.   1.  -1.   2.  -1.   0.   4.   4.   1.  -6.   4.  -5.
     0.   3.   9.  -8.  -2.  12. -14.   8.  -7.   7.  -5.   4.  -6.   6.
    -8.   0.   2.  -1.   0.   1.   0.  -4.   0.  -1.   1.]]]


In [112]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [122]:
A = (medical_data[:6,30:])
print(A)

[[ 4.  4.  5.  7.  3.  4.  2.  3.  0.  0.]
 [ 3.  5.  4.  4.  5.  5.  1.  1.  0.  1.]
 [10.  5.  4.  2.  2.  3.  2.  2.  1.  1.]
 [ 4.  4.  5.  7.  3.  4.  2.  3.  0.  0.]
 [ 3.  5.  4.  4.  5.  5.  1.  1.  0.  1.]
 [10.  5.  4.  2.  2.  3.  2.  2.  1.  1.]]


In [119]:
patient_2 = A[1,:]

In [120]:
print(patient_2)

[3. 5. 4. 4. 5. 5. 1. 1. 0. 1.]


In [123]:
patient_2_min = np.min(patient_2)

In [124]:
print(patient_2_min)

0.0


In [125]:
print(B)

[[[  1.   1.  -1.   1.  -1.   2.  -1.   0.   4.   4.   1.  -6.   4.  -5.
     0.   3.   9.  -8.  -2.  12. -14.   8.  -7.   7.  -5.   4.  -6.   6.
    -8.   0.   2.  -1.   0.   1.   0.  -4.   0.  -1.   1.]]]


In [150]:
A = [1, 2, -10, 6]

In [151]:
number_1 = np.max(A)

In [152]:
print(number_1)

6


In [154]:
x = 5
y = "my string"

In [155]:
x + 4

9

In [159]:
newstring = " Mus musculus "

In [161]:
newstring.split()

['Mus', 'musculus']

In [162]:
print(medical_data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]]


In [164]:
s = "WHEN on board H.M.S. Beagle, as naturalist"

In [171]:
s.count(b)

TypeError: must be str, not type

TypeError: must be str, not type